### ISSUE TITLE
How do you limit evaluation to only certain systems?

### ISSUE THREAD

**Issue by antifuchs** [hercules-ci/flake-compat-ci#1]
I'm trying to test my system configuration flake, and it is working very well! Unfortunately, hercules tries to build all the systems that are defined in my flake, and I only have a smaller set of builders available (while the flake defines darwin configurations and apps that ought to work on Darwin, I don't currently have a machine that I could use as a CI builder). 

Is there a way to restrict the flake build to only a certain set of system platforms?

**Comment by roberth** [comment]
The updated readme:
```
    ciNix = flake-compat-ci.lib.recurseIntoFlakeWith {
      flake = self;
      # Optional. Systems for which to perform CI.
      # By default, every system attr in the flake will be built.
      # Example: [ "x86_64-darwin" "aarch64-linux" ];
      systems = [ "x86_64-linux" ];
    };
```

You can always remove parts of a flake by post-processing the output of `recurseIntoFlakeWith`, if you need to specify things in a more fine-grained manner. The `systems` parameter seems like it should cover your use case though.
